# Generated by Django 6.0.4 on 2026-04-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images/games/', verbose_name='Изображение игры'),
        ),
    ]
